export enum Selectors {
  tr = 'tr',
  td = 'td',
  li = 'li',
  p = 'p',
  menu = '.po-menu-mobile > .po-icon',
  email = '#email',
  password = '#password',
  buttonLogin = '.gate-btn',
  overlay = '.po-table-overlay-content',
  menuIcon = 'po-menu-item .po-menu-short-label',
  buttonAdd = '[p-kind="primary"] > .po-button',
  buttonSave = '.po-button-modal-first-action > .po-button',
  modalAdd = '.po-modal-content',
  tableContainer = '.po-table-main-container',
  simpleFilter = '.po-page-list-filter-wrapper > .po-field-container-content > .po-input',
  buttonSearch = '.po-field-container-content > .po-field-icon-container-right > .po-icon',
  disclaimerDelete = '.po-disclaimer-remove',
  googleAddress = '.pac-item',
  buttonDelete = '.po-page-list-actions .po-button-default',
  toaster = '.alert',
}
