name: E2E Execution
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, development ]

jobs:
  E2E-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backoffice

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.x
          cache: npm
          cache-dependency-path: ./backoffice/package-lock.json

      - name: Install
        run: npm install

      - name: Remove old report
        run: rm -f ./cypress/report/html/** ./cypress/report/json/**

      - name: Test
        uses: cypress-io/github-action@v5.7.1
        with:
         project: ./backoffice
         command: npx cypress run
         headed: true
         
