name: E2E Execution
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, development ]

  schedule:
  - cron: '0 02 * * 1,4'

env: 
    LANG: "pt_BR.UTF-8"
    TZ: "America/Sao_Paulo"
    LC_ALL: "pt_BR.UTF-8"
    LANGUAGE: "pt_BR.UTF-8"

jobs:
  E2E-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backoffice

    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Set language
        run: |
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.x
          cache: npm
          cache-dependency-path: ./backoffice/package-lock.json

      - name: Install
        run: npm install

      - name: Remove old report
        run: rm -f ./cypress/report/html/** ./cypress/report/json/** ./cypress/report/xml/**

      - name: Test
        run: npm run cy:run
        continue-on-error: true

      - name: Html report
        uses: actions/upload-artifact@v3
        if: failed()
        with:
          name: cucumber-report
          path: ./backoffice/cypress/report/html/cucumber-report.html
          retention-days: 2

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        if: always()
        with:
          files: ./backoffice/cypress/report/xml/results_**.xml
