name: E2E Execution
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, development ]

jobs:
  E2E-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backoffice

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.x
          cache: npm
          cache-dependency-path: ./backoffice/package-lock.json

      - name: Install
        run: npm install

      - name: Test
        run: npm run cy:run
