name: E2E Execution
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, development ]

jobs:
  E2E-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.x
          cache: npm

      - name: Install
        working-directory: ./backoffice
        run: npm install

      - name: Test
        working-directory: ./backoffice
        run: npm cy:run
